title: Vinay's Blog
author: Vinay Panthea
email: vpanthena@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 This is my blog. It is fun to write it. 

# social links
twitter_username: N/A
github_username:  Vinay-Panthena

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
